// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhn5zvqcJdXJdu_3LIEfsr4UYP_un0RZM',
    appId: '1:356002469999:web:852f2ab49e89514bc9d59a',
    messagingSenderId: '356002469999',
    projectId: 'borealis-8f700',
    authDomain: 'borealis-8f700.firebaseapp.com',
    storageBucket: 'borealis-8f700.appspot.com',
    measurementId: 'G-7HX385WZ9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA76J9yEBAD396RAtbA_i8TYYeEjYN_1k',
    appId: '1:356002469999:android:a9ecddd96f421299c9d59a',
    messagingSenderId: '356002469999',
    projectId: 'borealis-8f700',
    storageBucket: 'borealis-8f700.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKsFJqgTKsm9qnZo5wYA2UEe3ktm5LxPc',
    appId: '1:356002469999:ios:f3743e01db8131a0c9d59a',
    messagingSenderId: '356002469999',
    projectId: 'borealis-8f700',
    storageBucket: 'borealis-8f700.appspot.com',
    iosClientId:
        '356002469999-26qdrsdhik2678ccmaajh1ucdm0116on.apps.googleusercontent.com',
    iosBundleId: 'com.example.borealis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKsFJqgTKsm9qnZo5wYA2UEe3ktm5LxPc',
    appId: '1:356002469999:ios:a1190da34b2b9e13c9d59a',
    messagingSenderId: '356002469999',
    projectId: 'borealis-8f700',
    storageBucket: 'borealis-8f700.appspot.com',
    iosClientId:
        '356002469999-aieb6i8rmbja0qg67e6kq2robdq5drd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.borealis.RunnerTests',
  );
}
